baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "Blazed Company"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "G-KFS2QS459D"
  google_tag_manager_id = "GTM-NMWQMKZ"

  [params.homepage]
    show_contact_box = true      # show / hide the contaxt box on the homepage
    show_services_button = false # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/Beaker-Dark.svg"
    mobile_height = "36px"
    desktop = "images/logo/Beaker-Dark.svg"
    desktop_height = "36px"
    alt = "Blazed Labs LLC"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@BlazedLabs"
    meta_twitter_creator = "@TylerRuffDev"
    meta_og_image = "https://blazed.sirv.com/logo/Wallpaper-Beaker.png"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '&copy;2023 <a href="https://blazedlabs.com/">Blazed Labs LLC</a>, <a href="https://ruff-manage.com/">Ruff Management Inc</a>.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
    weight = 2
